export const SET_EDITOR_CM = 'SET_EDITOR_CM';
export const CREATE_MAIN_STATES = 'CREATE_MAIN_STATES';
export const CLICK_CARD_VIEW = 'CLICK_CARD_VIEW';
export const CARD_ACTION = 'CARD_ACTION';
export const CHANGE_FIRST_RENDER = 'CHANGE_FIRST_RENDER';
export const DELETE_CARD = 'DELETE_CARD';
