export const SET_EDITOR_CM = 'SET_EDITOR_CM';
export const CREATE_PREACT_STATE = 'CREATE_PREACTS_TATE';
export const CLICK_CARD_VIEW = 'CLICK_CARD_VIEW';
export const CARD_ACTION = 'CARD_ACTION';
export const CHANGE_FIRST_RENDER = 'CHANGE_FIRST_RENDER';
