export const CREATE_MAIN_STATES = 'CREATE_MAIN_STATES';
export const CREATE_EMPTY_CARD = 'CREATE_EMPTY_CARD';
export const CLICK_CARD_VIEW = 'CLICK_CARD_VIEW';
export const CHANGE_CARD = 'CHANGE_CARD';
export const CHANGE_FIRST_RENDER = 'CHANGE_FIRST_RENDER';
export const DELETE_CARD = 'DELETE_CARD';
export const ADD_CARD_VERTICALLY = 'ADD_CARD_VERTICALLY';
export const ADD_CARD_RIGHT = 'ADD_CARD_RIGHT';
