export enum RootTypes {
  CREATE_MAIN_STATES = 'CREATE_MAIN_STATES',
  CREATE_EMPTY_CARD = 'CREATE_EMPTY_CARD',
  CLICK_CARD_VIEW = 'CLICK_CARD_VIEW',
  CHANGE_CARD = 'CHANGE_CARD',
  CHANGE_FIRST_RENDER = 'CHANGE_FIRST_RENDER',
  DELETE_CARD = 'DELETE_CARD',
  ADD_CARD_VERTICALLY = 'ADD_CARD_VERTICALLY',
  ADD_CARD_RIGHT = 'ADD_CARD_RIGHT',
}
